#!/usr/bin/python
#!flask/bin/python

#This is Jack Cahn and Alvin Leung's Project

from flask import Flask
from flask import request
from flask import url_for,render_template
from flask import session,request,redirect
from flask.ext import shelve

app = Flask(__name__)
app.secret_key="secret_key"
app.config['SHELVE_FILENAME'] = 'my_users.db'
shelve.init_app(app)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/about")
def about():
    return "<h1>About</h1>"

@app.route("/login",methods=['GET', 'POST'])
def login():
    if request.method=="GET":
        my_users = shelve.get_shelve('c')
        return render_template("login.html")

        d={'username':request.form['username'],
           'password':request.form['password']}
        button=request.form['button']
        if button=="login":
            s="%(username)s:%(password)s\n"%(d)
            return redirect("/")
        else: 
            return render_template("login.html")

@app.route("/form",methods=['GET','POST'])
def form():
    if request.method=="GET":
        return render_template("form.html")
        d={'name':request.form['username'],
           'HR':request.form['HR']}
        button=request.form['button']
        if button=="Submit":
            s="%(name)s:%(HR)s\n"%(d)
            return redirect("/")
            return render_template("render_template.html",d=d)
        else:
            return redirect("/")

@app.route("/register",methods=['GET','POST'])
def register():
    my_users = shelve.get_shelve('c')
    if request.method == 'GET':
        return render_template("register.html",error="")
    elif request.method == 'POST':
        user = request.form['user'].encode('ascii','ignore')
        pw = request.form['pass'].encode('ascii','ignore')
        if my_users.haskey(user):
            return render_template("register.html",error="Username already exists")
        else:
            userdb[user] = pw
            return redirect(url_for('home')) #Change to sign_in when sign in works

if __name__=="__main__":
    app.debug=True
    app.run(host="0.0.0.0",port=5005)
